name: circular_chart
description: Animated radial and pie charts for Flutter. Forked from https://github.com/xqwzts/flutter_circular_chart
version: 0.1.0
author: Gustavo Bonifacio Rodrigues <omykronbr@gmail.com>
homepage: https://github.com/GusRodrigues86/circular_charts

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"
